# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Remove the substring which is shared by the begining and end of all strings in a CharacterVector.
#'
#' @param cStrings The CharacterVector.
#' @param verbose Print verbose output?
#' @return CharacterVector with common begining and ending removed.
#'
smallestDifferentStrings <- function(cStrings, verbose = TRUE) {
    .Call('_rDIAUtils_smallestDifferentStrings', PACKAGE = 'rDIAUtils', cStrings, verbose)
}

